<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'console.command.messenger_failed_messages_retry' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/console/Command/Command.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Command/AbstractFailedMessagesCommand.php';
include_once $this->targetDirs[3].'/vendor/symfony/messenger/Command/FailedMessagesRetryCommand.php';

$this->privates['console.command.messenger_failed_messages_retry'] = $instance = new \Symfony\Component\Messenger\Command\FailedMessagesRetryCommand('failed', ($this->privates['messenger.transport.failed'] ?? $this->load('getMessenger_Transport_FailedService.php')), ($this->privates['messenger.routable_message_bus'] ?? $this->load('getMessenger_RoutableMessageBusService.php')), ($this->services['event_dispatcher'] ?? $this->getEventDispatcherService()), ($this->privates['messenger.retry.multiplier_retry_strategy.failed'] ?? $this->load('getMessenger_Retry_MultiplierRetryStrategy_FailedService.php')), ($this->privates['monolog.logger'] ?? $this->load('getMonolog_LoggerService.php')));

$instance->setName('messenger:failed:retry');

return $instance;
